server:
  port: 9606
spring:
  profiles:
    active:
    - develop
  
---

spring:
  profiles: product
  
---

spring:
  profiles: develop
fenkins:
  home: release
logging:
  file: ${fenkins.home}/logs/fenkins.log
