projects:
  - name: test1
    git:
      url: https://github.com/cheergoivan/Fenkins-back
      credential:
        username: cheergoivan@gmail.com
        password: 
    build:
      command: mvn clean1 package
      timeout: 10000
    deploy:
      command: test
      timeout: 10000
    notification:
      trigger: ALWAYS
      emails: [email1]
  - name: test2
    git:
      url: https://gitee.com/cheegoivan/FeastBooking
      credential:
        username: test
        password: test
    build:
      command: test
      timeout: 10000
    deploy:
      command: test
      timeout: 10000
    notification:
      trigger: ALWAYS
      emails: [email1, email2]
mail:
  host: smtp.163.com
  username: cheergoivan@163.com
  password: qwertyuiop123
  port: 465
