projects:
  - name: totp
    git:
      url: https://github.com/cheergoivan/totp-authenticator
      credential:
        username: cheergoivan@gmail.com
        password: asdfghjkl456
    build:
      command: mvn clean package
      timeout: 10000
    deploy:
      command: hhh
      timeout: 10000
    notification:
      trigger: ALWAYS
      emails: [email1]
  - name: test2
    git:
      url: https://gitee.com/cheegoivan/FeastBooking
      credential:
        username: test
        password: test
    build:
      command: test
      timeout: 10000
    deploy:
      command: test
      timeout: 10000
    notification:
      trigger: ALWAYS
      emails: [email1, email2]
mail:
  host: smtp.163.com
  username: cheergoivan@163.com
  password: qwertyuiop123
  port: 465
